### ISSUE TITLE
Does not handle object changes within array

### ISSUE THREAD

**Issue by filipot** [AsyncBanana/microdiff#11]
```javascript
import diff from "microdiff";

const obj1 = {
	array:[{test2:0}]
};
const obj2 = {
	array:[{test2:1}]
};

console.log(diff(obj1, obj2));
```
This ^ console logs an empty array. ([repl](https://svelte.dev/repl/7c03930ff8cb48de85399c7dd8b6f76c?version=3.44.1))

Are there any plans on supporting objects within arrays? If no, do you know about another library that do support this?

**Comment by AsyncBanana** [comment]
Thanks for reporting this! That should work. I will take a look at this soon.

**Comment by AsyncBanana** [comment]
Thanks again! This should be fixed in the latest version.
