### ISSUE TITLE
How about having index path for array be a number instead of a string?

### ISSUE THREAD

**Issue by filipot** [AsyncBanana/microdiff#12]
```svelte
<script>
import diff from "microdiff";

const array1 = [1];
const array2 = [2];
	
	
const obj1 = {0:1};
const obj2 = {0:2};

</script>

{JSON.stringify(diff(array1,array2))}
<br/>
{JSON.stringify(diff(obj1,obj2))}
```
Both diffs give the same result, which could be problematic:
```javascript
[{"path":["0"],"type":"CHANGE","value":2}]
[{"path":["0"],"type":"CHANGE","value":2}]
```
([repl](https://svelte.dev/repl/a8eaaeab49f54a2586314d321024699b?version=3.44.1))

My proposal is to differenciate between object and array by having array indexes be a number instead of a string, so that the result would be this instead:
```javascript
[{"path":[0],"type":"CHANGE","value":2}]
[{"path":["0"],"type":"CHANGE","value":2}]
```

So the path array will have this type: 
```typescript
 Array<string | number>
```

This would make it easier to create a patching function too

**Comment by AsyncBanana** [comment]
Good idea! I was planning on adding patching, and this would prevent accidental transformations between an object and an array. I will work on adding this and will hopefully release it in the next release.

**Comment by AsyncBanana** [comment]
In v1.2.0, array paths should be numbers instead of strings. If this does not work, let me know.
