### ISSUE TITLE
Is it possible to see the old value?

### ISSUE THREAD

**Issue by Simone-cogno** [AsyncBanana/microdiff#15]
Hello, it would be very nice to be able to see the old value in a CHANGE operation. Is it already possible? If not I think it would be easy to add right?

**Comment by AsyncBanana** [comment]
Currently, you can use the `path` property to access the old value by finding the value at the path in the old object. However, if enough people express interest in this, I might add the ability to directly access the old value (through an `oldValue` property).

**Comment by AsyncBanana** [comment]
`oldValue` should exist in `CHANGE` and `REMOVE` operations from v1.3.0 on.
