### ISSUE TITLE
Question: any recommendation on how to visualize the output?

### ISSUE THREAD

**Issue by kirillgroshkov** [AsyncBanana/microdiff#18]
I like the library. But is there a recommended way to visualize the output? I'm looking for something that looks like jest-diff output or "github PR changes", e.g just for the terminal?

**Comment by AsyncBanana** [comment]
Good question! Currently, there is no recommended way to visualize changes. However, it should not be difficult to make your own method of doing this, and if you make an open-source library for this, I would love to feature it on the Microdiff README. Also, #17 should help once it is merged.

**Comment by denis-bel** [comment]
> I like the library. But is there a recommended way to visualize the output? I'm looking for something that looks like jest-diff output or "github PR changes", e.g just for the terminal?

Hello, would you like to visualize the output like this one? 

![image](https://user-images.githubusercontent.com/71177596/157617658-7ffc723a-10f5-4713-9334-be2e5f71dd5c.png)

(Green - was created, Red - was deleted, Yellow - was changed)

**Comment by kirillgroshkov** [comment]
> Hello, would you like to visualize the output like this one?

Yes, exactly.

Like github visualizes differences. Or Jest.

**Comment by denis-bel** [comment]
> > Hello, would you like to visualize the output like this one?
> 
> Yes, exactly.
> 
> Like github visualizes differences. Or Jest.

Okay, I asked because GitHub cannot show that something has been changed. It shows that the content of the line was deleted and then added, but the microdiff has a CHANGE type. So it will be okay to have a third format for changed values?

**Comment by kirillgroshkov** [comment]
Aha, then I misunderstood.

No, I don't see the need for CHANGE type, but instead I expect to see "what exactly" is changed in that line. E.g if a string is changed, it would show in red the removed characters and in green the added characters.

**Comment by denis-bel** [comment]
So, consider these objects like old and new

```js
const oldObject = {
	a: 'value',
	b: 'old value'
};
const newObject = {
	b: 'another value',
	c: 'new value'
};
```
Would you like to get output like this?

<img width="183" alt="image" src="https://user-images.githubusercontent.com/71177596/157629962-4c6df516-0caa-456d-9ed3-cf601b1d6597.png">

**Comment by AsyncBanana** [comment]
Closing this because a solution to this should be developed separately.
