### ISSUE TITLE
Possible optimization: hashing 

### ISSUE THREAD

**Issue by LifeIsStrange** [AsyncBanana/microdiff#19]
Leverage hashing for detecting change much much faster than a deep comparison?
And microdiff would have optionally a backing buffer/cache of previous object hashes?

**Comment by denis-bel** [comment]
What do you propose to hash? If I understand you, you want to hash objects and compare hashes, and only if hashes are different, do comparison?

**Comment by AsyncBanana** [comment]
I think the user should do this themselves because this would increase code size, and for many things, a lack of changes is unlikely enough that the disadvantages outweigh the advantages.
