### ISSUE TITLE
UMD bundle

### ISSUE THREAD

**Issue by CheshireCaat** [AsyncBanana/microdiff#20]
Good day, and thanks for such awesome library! Are you planning to add separate builds like many other libraries do? I use your library for development under an old browser that doesn't support CommonJS format, and I constantly have to do custom UMD builds using rollup or other tools. It will be nice if you can add separate builds and possibly links to the CDN. I can try PR and implement it myself, but I'm very busy right now.

**Comment by AsyncBanana** [comment]
Thanks for the suggestion! I might replace the CommonJS module with this so then all mainstream JavaScript module formats will be supported. It shouldn't be too hard to implement because TypeScript supports it.

**Comment by AsyncBanana** [comment]
I have decided not to do this because this use case is so rare nowadays, and that would be extra weight, even if it is just for Node. However, it would be simple enough to convert Microdiff to UMD yourself.
