### ISSUE TITLE
support for NaN values

### ISSUE THREAD

**Issue by brainthinks** [AsyncBanana/microdiff#23]
Currently, `NaN` values always result in `CHANGE`, even though nothing changed.  Technically in JS, `NaN !== NaN`, so I understand that there is an argument for this behavior.  However, I think that having a `CHANGE` entry on EVERY diff when an object contains `NaN` is noise, and therefore unexpected / undesirable behavior.

I propose treating `NaN` values as equivalent, resulting in the following:

```javascript
diff({ testNaN: NaN }, { testNaN: NaN }) === [] // true
```

**Comment by AsyncBanana** [comment]
Fixed in 1.4.0
