### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by gustavopch** [AsyncBanana/microdiff#3]
I'm trying to `require('microdiff')` but it throws `ERR_REQUIRE_ESM`. I'm using Node.js 12. Don't you think CommonJS should still be supported?

**Comment by AsyncBanana** [comment]
You are probably right. I will work on adding CommonJS support and will tell you when it is added.

**Comment by AsyncBanana** [comment]
CommonJS should work now out of the box if you install v1.1.0+. You can use it like this
```js
const diff = require("microdiff").default
```
Tell me if you have any problems with it.
