### ISSUE TITLE
Add templates for issues

### ISSUE THREAD

**Issue by ericdrosado** [AsyncBanana/microdiff#30]
Issue templates are very helpful for a collaboration repo. When users identify a bug or want to add a new feature, you can provide templates so you can collect all the pertinent information you need to fix a bug or add a new feature. 

We recommend creating a “Report Bug” and “Feature Request” issue template. 

Some suggested prompts/questions you can add to a “Report Bug” template are:

* Briefly describe the bug
* What is the expected behavior?
* Please provide step by step instructions on how to reproduce the bug

Some suggested prompts/questions you can add to a “Feature Request” issue template are:

* Briefly describe your feature request
* What problem is this feature trying to solve?
* How do we know when the feature is complete?

**Comment by AsyncBanana** [comment]
Ok, I just created some issue templates. Let me know if you think anything should be changed.

**Comment by ericdrosado** [comment]
Templates look good to me! I'll go ahead and close this issue.  🚀
