### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ericdrosado** [AsyncBanana/microdiff#31]
Your README is in great shape! 🎉 

I would recommend adding:

* How to [contribute to your project](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)
* Mention your code of conduct

Depending on the complexity of your project, you might be interested in creating a [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file, but we recommend starting simple with the bullet points above, and once you start to see an increase in users interested in contributing, you should consider a `CONTRIBUTING.md` file so you don’t find yourself overwhelmed with questions from other users.

**Comment by AsyncBanana** [comment]
I just updated the README to include both of these. Is there anything that should be changed?

**Comment by ericdrosado** [comment]
The content looks great @AsyncBanana !
