### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by ericdrosado** [AsyncBanana/microdiff#32]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct. 

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

**Comment by AsyncBanana** [comment]
I just added a code of conduct based off of the Contributor Covenant.

**Comment by ericdrosado** [comment]
Fantastic! 🚀
