### ISSUE TITLE
get array removals as "DELETE"

### ISSUE THREAD

**Issue by blockiyt** [AsyncBanana/microdiff#36]
Hey, first of all, great little tool!
But I have a question: I have two arrays, and I want to see if something gets updated, or removed or added to the array.
In both arrays are JS Objects, and if on of the JS objects is removed, I want that the libary tells met that one thing got removed, out of one array, but instead what is happening is that I get a "change" for every entry because the index of the other objects has changed. Is there a way to realise this?

**Comment by AsyncBanana** [comment]
Currently this is not possible for performance reasons. However, to get around this, you could try using a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) with numbers as keys.

**Comment by blockiyt** [comment]
When I convert the array to a Map, and I change / add or remove something, I just get an empty array back:

`
const beforeMap = new Map(before.substitutions.map((s, index) => [index, s]))
const afterMap = new Map(after.substitutions.map((s, index) => [index, s]))

const diffs = diff(beforeMap, afterMap)
console.log(diffs)

`

**Comment by svobik7** [comment]
Hi @blockiyt, did you solve this somehow? I am facing the same issue currently.

**Comment by blockiyt** [comment]
@svobik7 sadly not really a "ready to use" one, I wrote myself a function, to check the diffs, and then to put it in arrays what changed  or what was created etc.

**Comment by svobik7** [comment]
> Currently this is not possible for performance reasons. However, to get around this, you could try using a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) with numbers as keys.

Could you please share an example of Map approach? I am getting the same empty result as @blockiyt

**Comment by sneko** [comment]
@AsyncBanana I would be also interested in a way to compare 2 arrays of objects with a unique property to extract `added/updated/removed/unchanged`.

I tried a few library but when dealing with ~10k items it's so long. Curious if you have a suggestion with your library, or another library to advise for this?

Thank you,

**Comment by sneko** [comment]
Just to follow up in case it helps someone:

I did a wrapper to compare 2 arrays of objects having a unique property. It does not consider the deep difference since the resulting value when there is any change is to end in the database.

```ts
// comparaison.ts

import diff from 'microdiff';

export interface GetDiffResult<Model> {
  added: Model[];
  removed: Model[];
  updated: Model[];
  unchanged: Model[];
}

export function getDiff<Model extends Record<ReferenceProperty, any>, ReferenceProperty extends string | number | symbol>(
  before: Map<ReferenceProperty, Model>,
  after: Map<ReferenceProperty, Model>
): GetDiffResult<Model> {
  const result: GetDiffResult<Model> = {
    added: [],
    removed: [],
    unchanged: [],
    updated: [],
  };

  for (const [afterModelReference, afterModel] of after) {
    const sameBeforeReferenceModel = before.get(afterModelReference);

    if (sameBeforeReferenceModel) {
      const beforeAfterModelDiff = diff(sameBeforeReferenceModel, afterModel);

      // `microdiff` won't return if unchange, so we can rely on the diff length to detect any change
      if (beforeAfterModelDiff.length > 0) {
        result.updated.push(afterModel);
      } else {
        result.unchanged.push(afterModel);
      }
    } else {
      result.added.push(afterModel);
    }
  }

  for (const [beforeModelReference, beforeModel] of before) {
    if (!after.has(beforeModelReference)) {
      result.removed.push(beforeModel);
    }
  }

  return result;
}
```


```ts
// comparaison.spec.ts

import { getDiff } from './comparaison';

describe('getDiff()', () => {
  it('should compare maps of objects', async () => {
    const before = new Map([
      [1, { id: 1, myProp: 1 }],
      [2, { id: 2, myProp: 2 }],
      [3, { id: 3, myProp: 3 }],
    ]);

    const after = new Map([
      [2, { id: 2, myProp: 222 }],
      [3, { id: 3, myProp: 3 }],
      [4, { id: 4, myProp: 4 }],
    ]);

    const diffResult = getDiff(before, after);

    expect(diffResult).toStrictEqual({
      added: [{ id: 4, myProp: 4 }],
      removed: [{ id: 1, myProp: 1 }],
      unchanged: [{ id: 3, myProp: 3 }],
      updated: [{ id: 2, myProp: 222 }],
    });
  });
});
```
