### ISSUE TITLE
Number.isNaN() might be faster?

### ISSUE THREAD

**Issue by leeoniya** [AsyncBanana/microdiff#4]
@AsyncBanana 

https://stackoverflow.com/questions/33164725/confusion-between-isnan-and-number-isnan-in-javascript/33165410#33165410

untested, but from the description sounds like it could be.

**Comment by leeoniya** [comment]
also, i'm no mathemetician, but lolwut?

![image](https://user-images.githubusercontent.com/43234/140625327-6ecef69e-40fa-4725-b119-0d3df08e74ae.png)

**Comment by AsyncBanana** [comment]
Yeah, I checked that out but the automatic transformation was needed for things like dates. 
Also, yes, I meant double the speed. Thanks for pointing that out as something that could be clarified. You could submit a PR if you want, or I could try to clarify it.

**Comment by AsyncBanana** [comment]
I have now clarified the speed, so I am going to close this.
