### ISSUE TITLE
Cannot use 'in' operator to search for ... in null

### ISSUE THREAD

**Issue by zarmin** [AsyncBanana/microdiff#7]
```
const diff = require('microdiff').default
const a1 = {"a": { "b": 1 }}
const a2 = {"a": null}
console.log(diff(a1, a2))
```

```
/Users/.../node_modules/microdiff/dist/index.cjs:8
		if (!(key in newObj)) {
		          ^

TypeError: Cannot use 'in' operator to search for 'b' in null
```

**Comment by AsyncBanana** [comment]
Thanks for reporting this! I will work on a fix, it should not take long.

**Comment by AsyncBanana** [comment]
Ok, this should be fixed now. Let me know if you continue to have problems with this in version v1.1.1+.

**Comment by AbdallahAbis** [comment]
@AsyncBanana I'm having same issue in `"microdiff": "^1.3.2"`

**Comment by AsyncBanana** [comment]
Could you send me the relevant code?

**Comment by AndreyMay** [comment]
getting the same issue (comparing arrays of objects with arrays inside)

**Comment by AsyncBanana** [comment]
Microdiff expects basic objects or arrays. I would handle any other values before passing them to the diff function.
